@startuml

[*] --> EsperandoComponentes

EsperandoComponentes --> EnsamblajeEnProceso : todos los componentes listos
EnsamblajeEnProceso --> PruebaDeCalidad : ensamblaje completado
PruebaDeCalidad --> Completado : calidad aprobada
PruebaDeCalidad --> ErrorEnProduccion : falla en calidad
ErrorEnProduccion --> EnsamblajeEnProceso : corrección completada

@enduml