@startuml

actor Usuario as usuario
participant Fabrica
participant EstacionDeTrabajo
participant Trabajador
participant Componente
participant LineaDeProduccion
participant CampanaDeGauss

usuario -> Fabrica: iniciarProduccion()
Fabrica -> LineaDeProduccion: iniciarLinea()
Fabrica -> EstacionDeTrabajo: iniciarTrabajo()

EstacionDeTrabajo -> Trabajador: operarMaquina()
Trabajador -> Componente: producirComponente()

Componente -> LineaDeProduccion: enviarComponente()

LineaDeProduccion -> CampanaDeGauss: ensamblarCampana()
CampanaDeGauss -> LineaDeProduccion: verificarCalidad()
CampanaDeGauss -> usuario: campana lista y verificada

@enduml